#define PJMEDIA_CODEC_L16_HAS_8KHZ_MONO 1
#define PJMEDIA_CODEC_L16_HAS_8KHZ_STEREO 1
#define PJMEDIA_CODEC_L16_HAS_16KHZ_MONO 1
#define PJMEDIA_CODEC_L16_HAS_16KHZ_STEREO 1
#define PJMEDIA_CODEC_L16_HAS_48KHZ_MONO 1
#define PJMEDIA_CODEC_L16_HAS_48KHZ_STEREO 1

#define PJMEDIA_CODEC_OPUS_DEFAULT_BIT_RATE 128000
#define PJMEDIA_CODEC_OPUS_DEFAULT_COMPLEXITY 10
#define PJMEDIA_CODEC_OPUS_DEFAULT_CBR PJ_TRUE

#define PJMEDIA_CONF_USE_AGC 0
#define PJMEDIA_SPEEX_AEC_USE_AGC 0

#define PJSUA_MAX_CALLS 255
#define PJSUA_MAX_ACC 64

#define PJSUA_DEFAULT_SND_USE_SW_CLOCK  PJ_TRUE

#define PJSUA_PRES_TIMER 30

#define PJ_EXCLUDE_BENCHMARK_TESTS 1

/* Enable WebRTC-related features for pjproject build */
#define PJMEDIA_HAS_WEBRTC_AEC 1

#define PJMEDIA_SRTP_HAS_AES_GCM_256      1
#define PJMEDIA_SRTP_HAS_AES_GCM_128      1

#define PJ_HAS_SSL_SOCK 1
#define PJMEDIA_SRTP_HAS_DTLS 1
#define PJ_ICE_MAX_CAND 64